name: Sync to Forge Education

on:
  push: # Déclenche la synchronisation pour absolument TOUS les pushs

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: L'IA récupère le code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Propulsion vers la Forge
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ""
        with:
          source-repo: "https://github.com/Supoz9/edge-ai-education.git"
          destination-repo: "https://barthelemy:${{ secrets.FORGE_TOKEN }}@forge.apps.education.fr/barthelemy/edge-ai-education.git"